name: La chef consciente
favicon: null
layout_spectrum: 0.73779
typography_spectrum: 0.6861508945003152
style: taylor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9637760266195983
  lightness: 0.2634844051208347
  saturation: 0.7201983528211713
  rhythmicContrast: 0.001650604885071516
purpose: []
